### ISSUE TITLE
Multiple opened tab caused the page to load either really long or forever

### ISSUE THREAD

**Issue by tien** [TalismanSociety/talisman-web#351] opened 2022-11-01 22:49 UTC
# Current behaviour

- First tab will load instantly
- Subsequent tabs will load either very slowly or forever
- Closing all others older tab would make the current tab finish loading

**Comment by tien** [comment] 2022-11-01 22:49
cc @helloitsbirdo

**Comment by helloitsbirdo** [comment] 2022-11-01 23:21
just on nom pools page

**Comment by JAhimaz** [comment] 2023-03-29 03:45
Duplicate of #327, will close.

**Closed by JAhimaz** 2023-03-29 03:45 UTC
Labels: bug
